# Generated by Django 2.1.7 on 2019-04-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=128)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Decks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('notes', models.CharField(max_length=256)),
                ('deck_format', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='contents',
            name='deck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtg.Decks'),
        ),
    ]
